printf -v preset "\e[0m"

printf -v pbold "\e[1m"
printf -v plight "\e[2m"
printf -v pitalic "\e[3m"
printf -v punderscore "\e[4m"
printf -v pblink "\e[5m"
printf -v preverse "\e[7m"
printf -v pinvisible "\e[8m"
printf -v pstrikethrough "\e[9m"

printf -v pblack "\e[30m"
printf -v pred "\e[31m"
printf -v pgreen "\e[32m"
printf -v pyellow "\e[33m"
printf -v pblue "\e[34m"
printf -v pmagenta "\e[35m"
printf -v pcyan "\e[36m"
printf -v pwhite "\e[37m"
